In [1]:
!pip install scipy

In [3]:
import numpy as np
from scipy.sparse import csr_matrix

In [4]:
#Defining two matrix
A=np.array([[1,2],[3,4]]) #(2*2 matrix)
B=np.array([[5,6],[7,8]])

In [5]:
#Calculating inverse of the Matrix
try:
    inverse_A=np.linalg.inv(A)
    print("Inverse of Matrix A: ",inverse_A)
except np.linalg.LinAlgError:
    print("Matrix is singlur and cannot inverted")

Inverse of Matrix A:  [[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
identity=np.eye(3)
print("Identity Matrix: ",identity )

Identity Matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# Create an Identity Matrix without using np.eye
size=3
identity=np.zeros((size,size))
for i in range(size):
    identity[i][i]=1
print("Identity Matrix without using np.eye: ",identity)

Identity Matrix without using np.eye:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# Creating a Diagonal Matrix
diagonal=np.diag([20,30,40])
print(diagonal)

[[20  0  0]
 [ 0 30  0]
 [ 0  0 40]]


In [12]:
# Creating a Diagonal Matrix without using np.diag
diagonal=[40,50,60]
matrix=np.zeros((len(diagonal),len(diagonal)))
for i in range(len(diagonal)):
    matrix[i][i]=diagonal[i]
print(matrix)

[[40.  0.  0.]
 [ 0. 50.  0.]
 [ 0.  0. 60.]]


In [13]:
#Creating Sparse Matrix using csr_matrix
sparse=csr_matrix([[0,0,1],[0,2,0],[3,0,0]])
print(sparse)

  (0, 2)	1
  (1, 1)	2
  (2, 0)	3


In [14]:
# Creating a Sparse Matrix without using csr_matrix
sparse=[[0,0,1],[0,2,0],[3,0,0]]
matrix=np.array(sparse)
print(matrix)

[[0 0 1]
 [0 2 0]
 [3 0 0]]
